export const Images = {
    check: require("../assets/check.png"),
    uncheck: require("../assets/uncheck.png"),
    backgroundimg: require("../assets/login-back.png"),
    profi: require("../assets/profileimg.png"),
    menu: require("../assets/menu.png"),
    bell: require("../assets/bell.png"),
    editicon: require("../assets/edit.png"),
    p1: require("../assets/p1.png"),
    face: require("../assets/face.png"),
    language: require("../assets/language.png"),
    p1email: require("../assets/user-mail.png"),
    p2: require("../assets/p2.png"),
    p3: require("../assets/p3.png"),
    p4: require("../assets/p4.png"),
    p5: require("../assets/p5.png"),
    stopWatch: require("../assets/stopwatch.png"),
    userImg: require("../assets/userImg.png"),
    mobile: require("../assets/mobile.png"),
    speedIcon: require("../assets/speed-icon-1.png"),
    checked: require("../assets/checked.png"),
    checked1: require("../assets/checked1.png"),
    unchecked1: require("../assets/unchecked1.png"),
    pendingrequest: require("../assets/pending-request.png"),
    carimg: require("../assets/my-rides.png"),
    msgimg: require("../assets/messages.png"),
    paymentimg: require("../assets/payment.png"),
    profileimg: require("../assets/profile.png"),
    profilemenuimg: require("../assets/profile_menu.png"),
    supportimg: require("../assets/support.png"),
    aboutimg: require("../assets/about.png"),
    signoutimg: require("../assets/signout.png"),
    back: require("../assets/back.png"),

    logo: require("../assets/icon.png"),
    logoelq: require("../assets/logo_elq.png"),
    loginwithFb: require("../assets/loginwithFb.png"),
    loginwithGoogle: require("../assets/loginwithGoogle.png"),

    greendot: require("../assets/pickup.png"),
    work: require("../assets/work.png"),
    findimg: require("../assets/find.png"),
    attorneys1: require("../assets/Attorney_demand.png"),
    attorneys2: require("../assets/Attorney_court.png"),
    attorneys3: require("../assets/Attorney_consult.png"),
    radiocheck: require("../assets/radiocheck.png"),
    radiouncheck: require("../assets/radiouncheck.png"),

    jobrequestmap: require("../assets/jobrequestmapcustomer.png"),
    reddot: require("../assets/drop.png"),
    car: require("../assets/car.png"),
    cornerimg: require("../assets/msgcornerimg.png"),
    msgsend: require("../assets/msgsend.png"),

    bluemastercard: require("../assets/bluemastercard.png"),
    dcb: require("../assets/dcb.png"),
    mastercardround: require("../assets/mastercardround.png"),
    jcb: require("../assets/jcb.png"),
    greentick: require("../assets/greentick.png"),
    visa: require("../assets/visa.png"),
    info: require("../assets/info.png"),
    dollar: require("../assets/dollar.png"),
    star: require("../assets/star1.png"),
    emptystar: require("../assets/emptystar.png"),
    clock: require("../assets/clock.png"),
}