import { Dimensions } from 'react-native'
import normalize from 'react-native-normalize'
import { COLOR } from './Color'
import { Images } from './Images'
const { width, height } = Dimensions.get('window')

export const LAYOUT = {
  window: { width, height },
  googleMapsApiKey: 'AIzaSyBQjTfzE_m26y8-jSYTVPvwbkuebEUOCTM',
  googleMapsStyle: {
    textInputContainer: { width: '100%', backgroundColor: COLOR.primary, justifyContent: 'center', borderTopWidth: 0 },
    description: { fontWeight: 'bold', color: '#fff' },
    textInput: { color: '#fff', backgroundColor: COLOR.primary, fontSize: normalize(16), height: 30 },
    predefinedPlacesDescription: { color: 'red' }
  },
  Coutrycode: [
    { label: "Alabama", value: "key0" },
    { label: "Alaska", value: "key1" },
    { label: "Arizona", value: "key2" },
    { label: "Arkansas", value: "key3" },
    { label: "Connecticut", value: "key4" },
    { label: "Delaware", value: "key5" },
    { label: "Florida", value: "key6" },
    { label: "Georgia", value: "key7" },
    { label: "Hawaii", value: "key8" },
    { label: "Idaho", value: "key9" },
    { label: "Illinois", value: "key10" },
    { label: "Indiana", value: "key11" },
    { label: "lowa", value: "key12" },
    { label: "Kansas", value: "key13" },
    { label: "Kentucky", value: "key14" },
    { label: "Louisiana", value: "key15" },
    { label: "Maine", value: "key16" },
    { label: "Maryland", value: "key17" },
    { label: "Massachusetts", value: "key18" },
    { label: "Michigan", value: "key19" },
    { label: "Minnesota", value: "key20" },
    { label: "Mississippi", value: "key21" },
    { label: "Missouri", value: "key22" },
    { label: "Montana", value: "key23" },
    { label: "Nebraska", value: "key24" },
    { label: "Nevada", value: "key25" },
    { label: "New Hampshire", value: "key26" },
    { label: "New Jersey", value: "key27" },
    { label: "New Mexico", value: "key28" },
    { label: "New York", value: "key29" },
    { label: "North Carolina", value: "key30" },
    { label: "North Dakota", value: "key31" },
    { label: "Ohio", value: "key32" },
    { label: "Oklahoma", value: "key33" },
    { label: "Oregon", value: "key34" },
    { label: "Pennysylvania", value: "key35" },
    { label: "Rhode lsland", value: "key36" },
    { label: "South Carolina", value: "key37" },
    { label: "South Dakota", value: "key38" },
    { label: "Tennessee", value: "key39" },
    { label: "Texas", value: "key40" },
    { label: "Utah", value: "key41" },
    { label: "Vermont", value: "key42" },
    { label: "Virginia", value: "key43" },
    { label: "Washington", value: "key44" },
    { label: "West Virginia", value: "key45" },
    { label: "Wisconsin", value: "key46" },
    { label: "Wyoming", value: "key47" },
  ],
  AttorneySideMenu: [
    { title: 'Pending Request', screen: "pendingrequest", img: Images.pendingrequest },
    { title: 'My Requests', screen: "myrequest", img: Images.carimg },
    { title: 'Messages', screen: "messages", img: Images.msgimg },
    { title: 'Payment', screen: "payment", img: Images.paymentimg },
    { title: 'Profile Settings', screen: "profile", img: Images.profilemenuimg },
    { title: 'Support & FAQ', screen: "support", img: Images.supportimg },
    { title: 'About Us', screen: "about", img: Images.aboutimg },
    { title: 'Sign Out', screen: "login", img: Images.signoutimg },
  ],

  ClientSideMenu: [
    { title: 'Request Attorney', screen: "requestattorney", img: Images.pendingrequest },
    { title: 'My Requests', screen: "myrequest", img: Images.carimg },
    { title: 'Messages', screen: "messages", img: Images.msgimg },
    { title: 'Payment', screen: "payment", img: Images.paymentimg },
    { title: 'Profile Settings', screen: "profile", img: Images.profilemenuimg },
    { title: 'Support & FAQ', screen: "support", img: Images.supportimg },
    { title: 'About Us', screen: "about", img: Images.aboutimg },
    { title: 'Sign Out', screen: "login", img: Images.signoutimg },
  ],
  RadioData: [
    { label: 'Traffic', value: 'Traffic' },
    { label: 'Criminal', value: 'Criminal' },
    { label: 'DWI/DUI', value: 'DWI/DUI' },
    { label: 'Municipal Ordinance', value: 'Municipal Ordinance' },
    { label: 'Criminal', value: 'Criminal2' },
    { label: 'Family', value: 'Family' },
    { label: 'Civil', value: 'Civil' },
    { label: 'Landlord/Tenant', value: 'Landlord/Tenant' }
  ],
  LanguageList: [
    { label: "Afar", value: "Afar" },
    { label: "Abkhazian", value: "Abkhazian" },
    { label: "Afrikaans", value: "Afrikaans" },
    { label: "Akan", value: "Akan" },
    { label: "Amharic", value: "Amharic" },
    { label: "Aragonese", value: "Aragonese" },
    { label: "Arabic", value: "Arabic" },
    { label: "Assamese", value: "Assamese" },
    { label: "Avar", value: "Avar" },
    { label: "Aymara", value: "Aymara" },
    { label: "Azerbaijani", value: "Azerbaijani" },
    { label: "Bashkir", value: "Bashkir" },
    { label: "Belarusian", value: "Belarusian" },
    { label: "Bulgarian", value: "Bulgarian" },
    { label: "Bihari", value: "Bihari" },
    { label: "Bislama", value: "Bislama" },
    { label: "Bambara", value: "Bambara" },
    { label: "Bengali", value: "Bengali" },
    { label: "Tibetan", value: "Tibetan" },
    { label: "Breton", value: "Breton" },
    { label: "Bosnian", value: "Bosnian" },
    { label: "Catalan", value: "Catalan" },
    { label: "Chechen", value: "Chechen" },
    { label: "Chamorro", value: "Chamorro" },
    { label: "Corsican", value: "Corsican" },
    { label: "Cree", value: "Cree" },
    { label: "Czech", value: "Czech" },
    { label: "Old Church Slavonic / Old Bulgarian", value: "Old Church Slavonic / Old Bulgarian" },
    { label: "Chuvash", value: "Chuvash" },
    { label: "Welsh", value: "Welsh" },
    { label: "Danish", value: "Danish" },
    { label: "German", value: "German" },
    { label: "Divehi", value: "Divehi" },
    { label: "Dzongkha", value: "Dzongkha" },
    { label: "Ewe", value: "Ewe" },
    { label: "Greek", value: "Greek" },
    { label: "English", value: "English" },
    { label: "Esperanto", value: "Esperanto" },
    { label: "Spanish", value: "Spanish" },
    { label: "Estonian", value: "Estonian" },
    { label: "Basque", value: "Basque" },
    { label: "Persian", value: "Persian" },
    { label: "Peul", value: "Peul" },
    { label: "Finnish", value: "Finnish" },
    { label: "Fijian", value: "Fijian" },
    { label: "Faroese", value: "Faroese" },
    { label: "French", value: "French" },
    { label: "West Frisian", value: "West Frisian" },
    { label: "Irish", value: "Irish" },
    { label: "Scottish Gaelic", value: "Scottish Gaelic" },
    { label: "Galician", value: "Galician" },
    { label: "Guarani", value: "Guarani" },
    { label: "Gujarati", value: "Gujarati" },
    { label: "Manx", value: "Manx" },
    { label: "Hausa", value: "Hausa" },
    { label: "Hebrew", value: "Hebrew" },
    { label: "Hindi", value: "Hindi" },
    { label: "Hiri Motu", value: "Hiri Motu" },
    { label: "Croatian", value: "Croatian" },
    { label: "Haitian", value: "Haitian" },
    { label: "Hungarian", value: "Hungarian" },
    { label: "Armenian", value: "Armenian" },
    { label: "Herero", value: "Herero" },
    { label: "Interlingua", value: "Interlingua" },
    { label: "Indonesian", value: "Indonesian" },
    { label: "Interlingue", value: "Interlingue" },
    { label: "Igbo", value: "Igbo" },
    { label: "Sichuan Yi", value: "Sichuan Yi" },
    { label: "Inupiak", value: "Inupiak" },
    { label: "Ido", value: "Ido" },
    { label: "Icelandic", value: "Icelandic" },
    { label: "Italian", value: "Italian" },
    { label: "Inuktitut", value: "Inuktitut" },
    { label: "Japanese", value: "Japanese" },
    { label: "Javanese", value: "Javanese" },
    { label: "Kongo", value: "Kongo" },
    { label: "Kikuyu", value: "Kikuyu" },
    { label: "Kuanyama", value: "Kuanyama" },
    { label: "Kazakh", value: "Kazakh" },
    { label: "Greenlandic", value: "Greenlandic" },
    { label: "Cambodian", value: "Cambodian" },
    { label: "Kannada", value: "Kannada" },
    { label: "Korean", value: "Korean" },
    { label: "Kanuri", value: "Kanuri" },
    { label: "Kashmiri", value: "Kashmiri" },
    { label: "Kurdish", value: "Kurdish" },
    { label: "Komi", value: "Komi" },
    { label: "Cornish", value: "Cornish" },
    { label: "Kirghiz", value: "Kirghiz" },
    { label: "Latin", value: "Latin" },
    { label: "Luxembourgish", value: "Luxembourgish" },
    { label: "Ganda", value: "Ganda" },
    { label: "Limburgian", value: "Limburgian" },
    { label: "Lingala", value: "Lingala" },
    { label: "Laotian", value: "Laotian" },
    { label: "Lithuanian", value: "Lithuanian" },
    { label: "Latvian", value: "Latvian" },
    { label: "Malagasy", value: "Malagasy" },
    { label: "Marshallese", value: "Marshallese" },
    { label: "Maori", value: "Maori" },
    { label: "Macedonian", value: "Macedonian" },
    { label: "Malayalam", value: "Malayalam" },
    { label: "Mongolian", value: "Mongolian" },
    { label: "Moldovan", value: "Moldovan" },
    { label: "Marathi", value: "Marathi" },
    { label: "Malay", value: "Malay" },
    { label: "Maltese", value: "Maltese" },
    { label: "Burmese", value: "Burmese" },
    { label: "Nauruan", value: "Nauruan" },
    { label: "North Ndebele", value: "North Ndebele" },
    { label: "Nepali", value: "Nepali" },
    { label: "Ndonga", value: "Ndonga" },
    { label: "Dutch", value: "Dutch" },
    { label: "Norwegian Nynorsk", value: "Norwegian Nynorsk" },
    { label: "Norwegian", value: "Norwegian" },
    { label: "South Ndebele", value: "South Ndebele" },
    { label: "Navajo", value: "Navajo" },
    { label: "Chichewa", value: "Chichewa" },
    { label: "Occitan", value: "Occitan" },
    { label: "Ojibwa", value: "Ojibwa" },
    { label: "Oromo", value: "Oromo" },
    { label: "Oriya", value: "Oriya" },
    { label: "Ossetian", value: "Ossetian" },
    { label: "Punjabi", value: "Punjabi" },
    { label: "Pali", value: "Pali" },
    { label: "Polish", value: "Polish" },
    { label: "Pashto", value: "Pashto" },
    { label: "Portuguese", value: "Portuguese" },
    { label: "Quechua", value: "Quechua" },
    { label: "Raeto Romance", value: "Raeto Romance" },
    { label: "Kirundi", value: "Kirundi" },
    { label: "Romanian", value: "Romanian" },
    { label: "Russian", value: "Russian" },
    { label: "Rwandi", value: "Rwandi" },
    { label: "Sanskrit", value: "Sanskrit" },
    { label: "Sardinian", value: "Sardinian" },
    { label: "Sindhi", value: "Sindhi" },
    { label: "Sango", value: "Sango" },
    { label: "Serbo-Croatian", value: "Serbo-Croatian" },
    { label: "Sinhalese", value: "Sinhalese" },
    { label: "Slovak", value: "Slovak" },
    { label: "Slovenian", value: "Slovenian" },
    { label: "Samoan", value: "Samoan" },
    { label: "Shona", value: "Shona" },
    { label: "Somalia", value: "Somalia" },
    { label: "Albanian", value: "Albanian" },
    { label: "Serbian", value: "Serbian" },
    { label: "Swati", value: "Swati" },
    { label: "Southern Sotho", value: "Southern Sotho" },
    { label: "Sundanese", value: "Sundanese" },
    { label: "Swedish", value: "Swedish" },
    { label: "Swahili", value: "Swahili" },
    { label: "Tamil", value: "Tamil" },
    { label: "Telugu", value: "Telugu" },
    { label: "Tajik", value: "Tajik" },
    { label: "Thai", value: "Thai" },
    { label: "Tigrinya", value: "Tigrinya" },
    { label: "Turkmen", value: "Turkmen" },
    { label: "Tagalog", value: "Tagalog" },
    { label: "Tswana", value: "Tswana" },
    { label: "Tonga", value: "Tonga" },
    { label: "Turkish", value: "Turkish" },
    { label: "Tsonga", value: "Tsonga" },
    { label: "Tatar", value: "Tatar" },
    { label: "Twi", value: "Twi" },
    { label: "Tahitian", value: "Tahitian" },
    { label: "Uyghur", value: "Uyghur" },
    { label: "Urdu", value: "Urdu" },
    { label: "Venda", value: "Venda" },
    { label: "Vietnamese", value: "Vietnamese" },
    { label: "Volapük", value: "Volapük" },
    { label: "Walloon", value: "Walloon" },
    { label: "Wolof", value: "Wolof" },
    { label: "Xhosa", value: "Xhosa" },
    { label: "Yiddish", value: "Yiddish" },
    { label: "Yoruba", value: "Yoruba" },
    { label: "Zhuang", value: "Zhuang" },
    { label: "Chinese", value: "Chinese" },
    { label: "Zulu", value: "Zulu" }
  ]
}